# Generated by Django 4.1.7 on 2023-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_rename_post_comment_posturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postUrl',
            field=models.CharField(max_length=250),
        ),
    ]
