# Generated by Django 4.1.7 on 2023-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_comment_posturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='miningData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vader_neg', models.FloatField()),
                ('vader_neu', models.FloatField()),
                ('vader_pos', models.FloatField()),
                ('vader_compound', models.FloatField()),
                ('roberta_neg', models.FloatField()),
                ('roberta_neu', models.FloatField()),
                ('roberta_pos', models.FloatField()),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('postUrl', models.URLField()),
            ],
        ),
    ]
